"""
exporter.py
-----------
Export color analysis results in multiple formats:
  - JSON (full structured data)
  - CSV  (frame-by-frame)
  - CSS variables
  - Tailwind config (colors section)
  - Adobe ASE swatch (binary format)
"""

import json
import csv
import io
import struct
from typing import List, Dict


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------

def to_json(analysis: Dict) -> str:
    """Serialize full analysis result to pretty JSON."""
    # Remove thumbnail data to keep JSON lean
    slim = {
        "metadata": analysis.get("metadata", {}),
        "scenes": analysis.get("scenes", []),
        "frames": [
            {k: v for k, v in f.items() if k != "thumbnail"}
            for f in analysis.get("frames", [])
        ],
    }
    return json.dumps(slim, indent=2)


# ---------------------------------------------------------------------------
# CSV
# ---------------------------------------------------------------------------

def to_csv(analysis: Dict) -> str:
    """Generate a flat CSV of frame-level dominant colors."""
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "frame_index", "frame_number", "timestamp", "timestamp_formatted",
        "mood", "avg_hex", "avg_r", "avg_g", "avg_b",
        "color_1_hex", "color_1_pct",
        "color_2_hex", "color_2_pct",
        "color_3_hex", "color_3_pct",
        "color_4_hex", "color_4_pct",
        "color_5_hex", "color_5_pct",
    ])

    for f in analysis.get("frames", []):
        dc = f.get("dominant_colors", [])
        avg = f.get("average_color", {})
        rgb = avg.get("rgb", {})

        row = [
            f.get("frame_index", ""),
            f.get("frame_number", ""),
            f.get("timestamp", ""),
            f.get("timestamp_formatted", ""),
            f.get("mood", ""),
            avg.get("hex", ""),
            rgb.get("r", ""),
            rgb.get("g", ""),
            rgb.get("b", ""),
        ]
        for i in range(5):
            if i < len(dc):
                row += [dc[i]["hex"], dc[i]["percentage"]]
            else:
                row += ["", ""]

        writer.writerow(row)

    return output.getvalue()


# ---------------------------------------------------------------------------
# CSS Variables
# ---------------------------------------------------------------------------

def to_css(analysis: Dict, prefix: str = "vc") -> str:
    """Generate CSS custom properties from scene palettes."""
    lines = [":root {", f"  /* Video Color Intelligence — {analysis.get('metadata', {}).get('filename', 'video')} */"]

    for scene in analysis.get("scenes", []):
        sn = scene["scene_number"]
        lines.append(f"\n  /* Scene {sn}: {scene['start_formatted']} → {scene['end_formatted']} */")
        for i, color in enumerate(scene.get("palette", [])[:8], 1):
            lines.append(f"  --{prefix}-scene{sn}-color{i}: {color['hex']};")

    # Global dominant: first scene's palette
    scenes = analysis.get("scenes", [])
    if scenes:
        lines.append("\n  /* Global dominant colors */")
        for i, color in enumerate(scenes[0].get("palette", [])[:5], 1):
            lines.append(f"  --{prefix}-primary{i}: {color['hex']};")

    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tailwind Config
# ---------------------------------------------------------------------------

def to_tailwind(analysis: Dict) -> str:
    """Generate a Tailwind CSS colors extension config."""
    colors = {}
    for scene in analysis.get("scenes", []):
        sn = scene["scene_number"]
        scene_colors = {}
        for i, color in enumerate(scene.get("palette", [])[:8], 1):
            scene_colors[str(i * 100)] = color["hex"]
        colors[f"scene{sn}"] = scene_colors

    config = {
        "theme": {
            "extend": {
                "colors": colors
            }
        }
    }
    return (
        "// tailwind.config.js — generated by Video Color Intelligence Analyzer\n"
        "module.exports = " + json.dumps(config, indent=2)
    )


# ---------------------------------------------------------------------------
# Adobe ASE (Adobe Swatch Exchange)
# ---------------------------------------------------------------------------

def to_ase(analysis: Dict) -> bytes:
    """
    Generate an Adobe ASE binary swatch file from scene palettes.
    ASE format: https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/
    """
    # Build color entries from all scenes
    colors = []
    for scene in analysis.get("scenes", []):
        sn = scene["scene_number"]
        for i, c in enumerate(scene.get("palette", [])[:5], 1):
            rgb = c["rgb"]
            name = f"Scene{sn}-{i} {c['hex']}"
            colors.append((name, rgb["r"] / 255.0, rgb["g"] / 255.0, rgb["b"] / 255.0))

    buf = io.BytesIO()

    # ASE Header
    buf.write(b"ASEF")           # signature
    buf.write(struct.pack(">HH", 1, 0))  # version 1.0
    buf.write(struct.pack(">I", len(colors)))  # number of blocks

    for name, r, g, b in colors:
        # Block type: 0x0001 = color entry
        name_utf16 = (name + "\x00").encode("utf-16-be")
        color_model = b"RGB "
        color_data = struct.pack(">fff", r, g, b)
        color_type = struct.pack(">H", 0)  # 0 = Global

        block_data = (
            struct.pack(">H", len(name) + 1) +
            name_utf16 +
            color_model +
            color_data +
            color_type
        )
        buf.write(struct.pack(">HI", 0x0001, len(block_data)))
        buf.write(block_data)

    return buf.getvalue()
